// Code generated by ent, DO NOT EDIT.

package subscriptionmatch

import (
	"time"
)

const (
	// Label holds the string label denoting the subscriptionmatch type in the database.
	Label = "subscription_match"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldMatchID holds the string denoting the match_id field in the database.
	FieldMatchID = "match_id"
	// FieldPlayerID holds the string denoting the player_id field in the database.
	FieldPlayerID = "player_id"
	// FieldPlayerSlot holds the string denoting the player_slot field in the database.
	FieldPlayerSlot = "player_slot"
	// FieldRadiantWin holds the string denoting the radiant_win field in the database.
	FieldRadiantWin = "radiant_win"
	// FieldDuration holds the string denoting the duration field in the database.
	FieldDuration = "duration"
	// FieldGameMode holds the string denoting the game_mode field in the database.
	FieldGameMode = "game_mode"
	// FieldLobbyType holds the string denoting the lobby_type field in the database.
	FieldLobbyType = "lobby_type"
	// FieldHeroID holds the string denoting the hero_id field in the database.
	FieldHeroID = "hero_id"
	// FieldStartTime holds the string denoting the start_time field in the database.
	FieldStartTime = "start_time"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldKills holds the string denoting the kills field in the database.
	FieldKills = "kills"
	// FieldDeaths holds the string denoting the deaths field in the database.
	FieldDeaths = "deaths"
	// FieldAssists holds the string denoting the assists field in the database.
	FieldAssists = "assists"
	// FieldSkill holds the string denoting the skill field in the database.
	FieldSkill = "skill"
	// FieldLeaverStatus holds the string denoting the leaver_status field in the database.
	FieldLeaverStatus = "leaver_status"
	// FieldPartySize holds the string denoting the party_size field in the database.
	FieldPartySize = "party_size"
	// Table holds the table name of the subscriptionmatch in the database.
	Table = "subscription_matches"
)

// Columns holds all SQL columns for subscriptionmatch fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldMatchID,
	FieldPlayerID,
	FieldPlayerSlot,
	FieldRadiantWin,
	FieldDuration,
	FieldGameMode,
	FieldLobbyType,
	FieldHeroID,
	FieldStartTime,
	FieldVersion,
	FieldKills,
	FieldDeaths,
	FieldAssists,
	FieldSkill,
	FieldLeaverStatus,
	FieldPartySize,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
)
