// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// HerosColumns holds the columns for the "heros" table.
	HerosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "hero_id", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString},
		{Name: "localized_name", Type: field.TypeString},
	}
	// HerosTable holds the schema information for the "heros" table.
	HerosTable = &schema.Table{
		Name:       "heros",
		Columns:    HerosColumns,
		PrimaryKey: []*schema.Column{HerosColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "hero_hero_id",
				Unique:  false,
				Columns: []*schema.Column{HerosColumns[3]},
			},
		},
	}
	// SubscriptionsColumns holds the columns for the "subscriptions" table.
	SubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "group_id", Type: field.TypeInt},
		{Name: "steam_id", Type: field.TypeString},
		{Name: "alias", Type: field.TypeString},
	}
	// SubscriptionsTable holds the schema information for the "subscriptions" table.
	SubscriptionsTable = &schema.Table{
		Name:       "subscriptions",
		Columns:    SubscriptionsColumns,
		PrimaryKey: []*schema.Column{SubscriptionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "subscription_group_id",
				Unique:  false,
				Columns: []*schema.Column{SubscriptionsColumns[3]},
			},
			{
				Name:    "subscription_steam_id",
				Unique:  false,
				Columns: []*schema.Column{SubscriptionsColumns[4]},
			},
		},
	}
	// SubscriptionMatchesColumns holds the columns for the "subscription_matches" table.
	SubscriptionMatchesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "match_id", Type: field.TypeInt64},
		{Name: "player_id", Type: field.TypeString},
		{Name: "player_slot", Type: field.TypeInt},
		{Name: "radiant_win", Type: field.TypeBool},
		{Name: "duration", Type: field.TypeInt},
		{Name: "game_mode", Type: field.TypeInt},
		{Name: "lobby_type", Type: field.TypeInt},
		{Name: "hero_id", Type: field.TypeInt},
		{Name: "start_time", Type: field.TypeInt},
		{Name: "version", Type: field.TypeInt},
		{Name: "kills", Type: field.TypeInt},
		{Name: "deaths", Type: field.TypeInt},
		{Name: "assists", Type: field.TypeInt},
		{Name: "skill", Type: field.TypeInt, Nullable: true},
		{Name: "leaver_status", Type: field.TypeInt},
		{Name: "party_size", Type: field.TypeInt},
	}
	// SubscriptionMatchesTable holds the schema information for the "subscription_matches" table.
	SubscriptionMatchesTable = &schema.Table{
		Name:       "subscription_matches",
		Columns:    SubscriptionMatchesColumns,
		PrimaryKey: []*schema.Column{SubscriptionMatchesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		HerosTable,
		SubscriptionsTable,
		SubscriptionMatchesTable,
	}
)

func init() {
}
