// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Bpazy/behappy/ent/hero"
	"github.com/Bpazy/behappy/ent/predicate"
)

// HeroUpdate is the builder for updating Hero entities.
type HeroUpdate struct {
	config
	hooks    []Hook
	mutation *HeroMutation
}

// Where appends a list predicates to the HeroUpdate builder.
func (hu *HeroUpdate) Where(ps ...predicate.Hero) *HeroUpdate {
	hu.mutation.Where(ps...)
	return hu
}

// SetUpdateTime sets the "update_time" field.
func (hu *HeroUpdate) SetUpdateTime(t time.Time) *HeroUpdate {
	hu.mutation.SetUpdateTime(t)
	return hu
}

// SetHeroID sets the "hero_id" field.
func (hu *HeroUpdate) SetHeroID(i int) *HeroUpdate {
	hu.mutation.ResetHeroID()
	hu.mutation.SetHeroID(i)
	return hu
}

// AddHeroID adds i to the "hero_id" field.
func (hu *HeroUpdate) AddHeroID(i int) *HeroUpdate {
	hu.mutation.AddHeroID(i)
	return hu
}

// SetName sets the "name" field.
func (hu *HeroUpdate) SetName(s string) *HeroUpdate {
	hu.mutation.SetName(s)
	return hu
}

// SetLocalizedName sets the "localized_name" field.
func (hu *HeroUpdate) SetLocalizedName(s string) *HeroUpdate {
	hu.mutation.SetLocalizedName(s)
	return hu
}

// Mutation returns the HeroMutation object of the builder.
func (hu *HeroUpdate) Mutation() *HeroMutation {
	return hu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (hu *HeroUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	hu.defaults()
	if len(hu.hooks) == 0 {
		affected, err = hu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*HeroMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			hu.mutation = mutation
			affected, err = hu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(hu.hooks) - 1; i >= 0; i-- {
			if hu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = hu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, hu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (hu *HeroUpdate) SaveX(ctx context.Context) int {
	affected, err := hu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (hu *HeroUpdate) Exec(ctx context.Context) error {
	_, err := hu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hu *HeroUpdate) ExecX(ctx context.Context) {
	if err := hu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (hu *HeroUpdate) defaults() {
	if _, ok := hu.mutation.UpdateTime(); !ok {
		v := hero.UpdateDefaultUpdateTime()
		hu.mutation.SetUpdateTime(v)
	}
}

func (hu *HeroUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   hero.Table,
			Columns: hero.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: hero.FieldID,
			},
		},
	}
	if ps := hu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := hu.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: hero.FieldUpdateTime,
		})
	}
	if value, ok := hu.mutation.HeroID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: hero.FieldHeroID,
		})
	}
	if value, ok := hu.mutation.AddedHeroID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: hero.FieldHeroID,
		})
	}
	if value, ok := hu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: hero.FieldName,
		})
	}
	if value, ok := hu.mutation.LocalizedName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: hero.FieldLocalizedName,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, hu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hero.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// HeroUpdateOne is the builder for updating a single Hero entity.
type HeroUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HeroMutation
}

// SetUpdateTime sets the "update_time" field.
func (huo *HeroUpdateOne) SetUpdateTime(t time.Time) *HeroUpdateOne {
	huo.mutation.SetUpdateTime(t)
	return huo
}

// SetHeroID sets the "hero_id" field.
func (huo *HeroUpdateOne) SetHeroID(i int) *HeroUpdateOne {
	huo.mutation.ResetHeroID()
	huo.mutation.SetHeroID(i)
	return huo
}

// AddHeroID adds i to the "hero_id" field.
func (huo *HeroUpdateOne) AddHeroID(i int) *HeroUpdateOne {
	huo.mutation.AddHeroID(i)
	return huo
}

// SetName sets the "name" field.
func (huo *HeroUpdateOne) SetName(s string) *HeroUpdateOne {
	huo.mutation.SetName(s)
	return huo
}

// SetLocalizedName sets the "localized_name" field.
func (huo *HeroUpdateOne) SetLocalizedName(s string) *HeroUpdateOne {
	huo.mutation.SetLocalizedName(s)
	return huo
}

// Mutation returns the HeroMutation object of the builder.
func (huo *HeroUpdateOne) Mutation() *HeroMutation {
	return huo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (huo *HeroUpdateOne) Select(field string, fields ...string) *HeroUpdateOne {
	huo.fields = append([]string{field}, fields...)
	return huo
}

// Save executes the query and returns the updated Hero entity.
func (huo *HeroUpdateOne) Save(ctx context.Context) (*Hero, error) {
	var (
		err  error
		node *Hero
	)
	huo.defaults()
	if len(huo.hooks) == 0 {
		node, err = huo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*HeroMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			huo.mutation = mutation
			node, err = huo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(huo.hooks) - 1; i >= 0; i-- {
			if huo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = huo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, huo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Hero)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from HeroMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (huo *HeroUpdateOne) SaveX(ctx context.Context) *Hero {
	node, err := huo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (huo *HeroUpdateOne) Exec(ctx context.Context) error {
	_, err := huo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (huo *HeroUpdateOne) ExecX(ctx context.Context) {
	if err := huo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (huo *HeroUpdateOne) defaults() {
	if _, ok := huo.mutation.UpdateTime(); !ok {
		v := hero.UpdateDefaultUpdateTime()
		huo.mutation.SetUpdateTime(v)
	}
}

func (huo *HeroUpdateOne) sqlSave(ctx context.Context) (_node *Hero, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   hero.Table,
			Columns: hero.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: hero.FieldID,
			},
		},
	}
	id, ok := huo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Hero.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := huo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hero.FieldID)
		for _, f := range fields {
			if !hero.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != hero.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := huo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := huo.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: hero.FieldUpdateTime,
		})
	}
	if value, ok := huo.mutation.HeroID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: hero.FieldHeroID,
		})
	}
	if value, ok := huo.mutation.AddedHeroID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: hero.FieldHeroID,
		})
	}
	if value, ok := huo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: hero.FieldName,
		})
	}
	if value, ok := huo.mutation.LocalizedName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: hero.FieldLocalizedName,
		})
	}
	_node = &Hero{config: huo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, huo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hero.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
