// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Bpazy/behappy/ent/hero"
)

// HeroCreate is the builder for creating a Hero entity.
type HeroCreate struct {
	config
	mutation *HeroMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (hc *HeroCreate) SetCreateTime(t time.Time) *HeroCreate {
	hc.mutation.SetCreateTime(t)
	return hc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (hc *HeroCreate) SetNillableCreateTime(t *time.Time) *HeroCreate {
	if t != nil {
		hc.SetCreateTime(*t)
	}
	return hc
}

// SetUpdateTime sets the "update_time" field.
func (hc *HeroCreate) SetUpdateTime(t time.Time) *HeroCreate {
	hc.mutation.SetUpdateTime(t)
	return hc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (hc *HeroCreate) SetNillableUpdateTime(t *time.Time) *HeroCreate {
	if t != nil {
		hc.SetUpdateTime(*t)
	}
	return hc
}

// SetHeroID sets the "hero_id" field.
func (hc *HeroCreate) SetHeroID(i int) *HeroCreate {
	hc.mutation.SetHeroID(i)
	return hc
}

// SetName sets the "name" field.
func (hc *HeroCreate) SetName(s string) *HeroCreate {
	hc.mutation.SetName(s)
	return hc
}

// SetLocalizedName sets the "localized_name" field.
func (hc *HeroCreate) SetLocalizedName(s string) *HeroCreate {
	hc.mutation.SetLocalizedName(s)
	return hc
}

// Mutation returns the HeroMutation object of the builder.
func (hc *HeroCreate) Mutation() *HeroMutation {
	return hc.mutation
}

// Save creates the Hero in the database.
func (hc *HeroCreate) Save(ctx context.Context) (*Hero, error) {
	var (
		err  error
		node *Hero
	)
	hc.defaults()
	if len(hc.hooks) == 0 {
		if err = hc.check(); err != nil {
			return nil, err
		}
		node, err = hc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*HeroMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = hc.check(); err != nil {
				return nil, err
			}
			hc.mutation = mutation
			if node, err = hc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(hc.hooks) - 1; i >= 0; i-- {
			if hc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = hc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, hc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Hero)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from HeroMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (hc *HeroCreate) SaveX(ctx context.Context) *Hero {
	v, err := hc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hc *HeroCreate) Exec(ctx context.Context) error {
	_, err := hc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hc *HeroCreate) ExecX(ctx context.Context) {
	if err := hc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (hc *HeroCreate) defaults() {
	if _, ok := hc.mutation.CreateTime(); !ok {
		v := hero.DefaultCreateTime()
		hc.mutation.SetCreateTime(v)
	}
	if _, ok := hc.mutation.UpdateTime(); !ok {
		v := hero.DefaultUpdateTime()
		hc.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hc *HeroCreate) check() error {
	if _, ok := hc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Hero.create_time"`)}
	}
	if _, ok := hc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Hero.update_time"`)}
	}
	if _, ok := hc.mutation.HeroID(); !ok {
		return &ValidationError{Name: "hero_id", err: errors.New(`ent: missing required field "Hero.hero_id"`)}
	}
	if _, ok := hc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Hero.name"`)}
	}
	if _, ok := hc.mutation.LocalizedName(); !ok {
		return &ValidationError{Name: "localized_name", err: errors.New(`ent: missing required field "Hero.localized_name"`)}
	}
	return nil
}

func (hc *HeroCreate) sqlSave(ctx context.Context) (*Hero, error) {
	_node, _spec := hc.createSpec()
	if err := sqlgraph.CreateNode(ctx, hc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (hc *HeroCreate) createSpec() (*Hero, *sqlgraph.CreateSpec) {
	var (
		_node = &Hero{config: hc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: hero.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: hero.FieldID,
			},
		}
	)
	if value, ok := hc.mutation.CreateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: hero.FieldCreateTime,
		})
		_node.CreateTime = value
	}
	if value, ok := hc.mutation.UpdateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: hero.FieldUpdateTime,
		})
		_node.UpdateTime = value
	}
	if value, ok := hc.mutation.HeroID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: hero.FieldHeroID,
		})
		_node.HeroID = value
	}
	if value, ok := hc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: hero.FieldName,
		})
		_node.Name = value
	}
	if value, ok := hc.mutation.LocalizedName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: hero.FieldLocalizedName,
		})
		_node.LocalizedName = value
	}
	return _node, _spec
}

// HeroCreateBulk is the builder for creating many Hero entities in bulk.
type HeroCreateBulk struct {
	config
	builders []*HeroCreate
}

// Save creates the Hero entities in the database.
func (hcb *HeroCreateBulk) Save(ctx context.Context) ([]*Hero, error) {
	specs := make([]*sqlgraph.CreateSpec, len(hcb.builders))
	nodes := make([]*Hero, len(hcb.builders))
	mutators := make([]Mutator, len(hcb.builders))
	for i := range hcb.builders {
		func(i int, root context.Context) {
			builder := hcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HeroMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, hcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, hcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, hcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (hcb *HeroCreateBulk) SaveX(ctx context.Context) []*Hero {
	v, err := hcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hcb *HeroCreateBulk) Exec(ctx context.Context) error {
	_, err := hcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hcb *HeroCreateBulk) ExecX(ctx context.Context) {
	if err := hcb.Exec(ctx); err != nil {
		panic(err)
	}
}
