// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Bpazy/behappy/ent/hero"
	"github.com/Bpazy/behappy/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	heroMixin := schema.Hero{}.Mixin()
	heroMixinFields0 := heroMixin[0].Fields()
	_ = heroMixinFields0
	heroFields := schema.Hero{}.Fields()
	_ = heroFields
	// heroDescCreateTime is the schema descriptor for create_time field.
	heroDescCreateTime := heroMixinFields0[0].Descriptor()
	// hero.DefaultCreateTime holds the default value on creation for the create_time field.
	hero.DefaultCreateTime = heroDescCreateTime.Default.(func() time.Time)
	// heroDescUpdateTime is the schema descriptor for update_time field.
	heroDescUpdateTime := heroMixinFields0[1].Descriptor()
	// hero.DefaultUpdateTime holds the default value on creation for the update_time field.
	hero.DefaultUpdateTime = heroDescUpdateTime.Default.(func() time.Time)
	// hero.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	hero.UpdateDefaultUpdateTime = heroDescUpdateTime.UpdateDefault.(func() time.Time)
}
