// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Bpazy/behappy/ent/predicate"
	"github.com/Bpazy/behappy/ent/subscriptionmatch"
)

// SubscriptionMatchQuery is the builder for querying SubscriptionMatch entities.
type SubscriptionMatchQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.SubscriptionMatch
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SubscriptionMatchQuery builder.
func (smq *SubscriptionMatchQuery) Where(ps ...predicate.SubscriptionMatch) *SubscriptionMatchQuery {
	smq.predicates = append(smq.predicates, ps...)
	return smq
}

// Limit adds a limit step to the query.
func (smq *SubscriptionMatchQuery) Limit(limit int) *SubscriptionMatchQuery {
	smq.limit = &limit
	return smq
}

// Offset adds an offset step to the query.
func (smq *SubscriptionMatchQuery) Offset(offset int) *SubscriptionMatchQuery {
	smq.offset = &offset
	return smq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (smq *SubscriptionMatchQuery) Unique(unique bool) *SubscriptionMatchQuery {
	smq.unique = &unique
	return smq
}

// Order adds an order step to the query.
func (smq *SubscriptionMatchQuery) Order(o ...OrderFunc) *SubscriptionMatchQuery {
	smq.order = append(smq.order, o...)
	return smq
}

// First returns the first SubscriptionMatch entity from the query.
// Returns a *NotFoundError when no SubscriptionMatch was found.
func (smq *SubscriptionMatchQuery) First(ctx context.Context) (*SubscriptionMatch, error) {
	nodes, err := smq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{subscriptionmatch.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (smq *SubscriptionMatchQuery) FirstX(ctx context.Context) *SubscriptionMatch {
	node, err := smq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SubscriptionMatch ID from the query.
// Returns a *NotFoundError when no SubscriptionMatch ID was found.
func (smq *SubscriptionMatchQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = smq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{subscriptionmatch.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (smq *SubscriptionMatchQuery) FirstIDX(ctx context.Context) int {
	id, err := smq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SubscriptionMatch entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SubscriptionMatch entity is found.
// Returns a *NotFoundError when no SubscriptionMatch entities are found.
func (smq *SubscriptionMatchQuery) Only(ctx context.Context) (*SubscriptionMatch, error) {
	nodes, err := smq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{subscriptionmatch.Label}
	default:
		return nil, &NotSingularError{subscriptionmatch.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (smq *SubscriptionMatchQuery) OnlyX(ctx context.Context) *SubscriptionMatch {
	node, err := smq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SubscriptionMatch ID in the query.
// Returns a *NotSingularError when more than one SubscriptionMatch ID is found.
// Returns a *NotFoundError when no entities are found.
func (smq *SubscriptionMatchQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = smq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{subscriptionmatch.Label}
	default:
		err = &NotSingularError{subscriptionmatch.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (smq *SubscriptionMatchQuery) OnlyIDX(ctx context.Context) int {
	id, err := smq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SubscriptionMatches.
func (smq *SubscriptionMatchQuery) All(ctx context.Context) ([]*SubscriptionMatch, error) {
	if err := smq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return smq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (smq *SubscriptionMatchQuery) AllX(ctx context.Context) []*SubscriptionMatch {
	nodes, err := smq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SubscriptionMatch IDs.
func (smq *SubscriptionMatchQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := smq.Select(subscriptionmatch.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (smq *SubscriptionMatchQuery) IDsX(ctx context.Context) []int {
	ids, err := smq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (smq *SubscriptionMatchQuery) Count(ctx context.Context) (int, error) {
	if err := smq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return smq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (smq *SubscriptionMatchQuery) CountX(ctx context.Context) int {
	count, err := smq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (smq *SubscriptionMatchQuery) Exist(ctx context.Context) (bool, error) {
	if err := smq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return smq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (smq *SubscriptionMatchQuery) ExistX(ctx context.Context) bool {
	exist, err := smq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SubscriptionMatchQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (smq *SubscriptionMatchQuery) Clone() *SubscriptionMatchQuery {
	if smq == nil {
		return nil
	}
	return &SubscriptionMatchQuery{
		config:     smq.config,
		limit:      smq.limit,
		offset:     smq.offset,
		order:      append([]OrderFunc{}, smq.order...),
		predicates: append([]predicate.SubscriptionMatch{}, smq.predicates...),
		// clone intermediate query.
		sql:    smq.sql.Clone(),
		path:   smq.path,
		unique: smq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SubscriptionMatch.Query().
//		GroupBy(subscriptionmatch.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (smq *SubscriptionMatchQuery) GroupBy(field string, fields ...string) *SubscriptionMatchGroupBy {
	grbuild := &SubscriptionMatchGroupBy{config: smq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := smq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return smq.sqlQuery(ctx), nil
	}
	grbuild.label = subscriptionmatch.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.SubscriptionMatch.Query().
//		Select(subscriptionmatch.FieldCreateTime).
//		Scan(ctx, &v)
func (smq *SubscriptionMatchQuery) Select(fields ...string) *SubscriptionMatchSelect {
	smq.fields = append(smq.fields, fields...)
	selbuild := &SubscriptionMatchSelect{SubscriptionMatchQuery: smq}
	selbuild.label = subscriptionmatch.Label
	selbuild.flds, selbuild.scan = &smq.fields, selbuild.Scan
	return selbuild
}

func (smq *SubscriptionMatchQuery) prepareQuery(ctx context.Context) error {
	for _, f := range smq.fields {
		if !subscriptionmatch.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if smq.path != nil {
		prev, err := smq.path(ctx)
		if err != nil {
			return err
		}
		smq.sql = prev
	}
	return nil
}

func (smq *SubscriptionMatchQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SubscriptionMatch, error) {
	var (
		nodes = []*SubscriptionMatch{}
		_spec = smq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*SubscriptionMatch).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &SubscriptionMatch{config: smq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, smq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (smq *SubscriptionMatchQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := smq.querySpec()
	_spec.Node.Columns = smq.fields
	if len(smq.fields) > 0 {
		_spec.Unique = smq.unique != nil && *smq.unique
	}
	return sqlgraph.CountNodes(ctx, smq.driver, _spec)
}

func (smq *SubscriptionMatchQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := smq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (smq *SubscriptionMatchQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   subscriptionmatch.Table,
			Columns: subscriptionmatch.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: subscriptionmatch.FieldID,
			},
		},
		From:   smq.sql,
		Unique: true,
	}
	if unique := smq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := smq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionmatch.FieldID)
		for i := range fields {
			if fields[i] != subscriptionmatch.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := smq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := smq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := smq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := smq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (smq *SubscriptionMatchQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(smq.driver.Dialect())
	t1 := builder.Table(subscriptionmatch.Table)
	columns := smq.fields
	if len(columns) == 0 {
		columns = subscriptionmatch.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if smq.sql != nil {
		selector = smq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if smq.unique != nil && *smq.unique {
		selector.Distinct()
	}
	for _, p := range smq.predicates {
		p(selector)
	}
	for _, p := range smq.order {
		p(selector)
	}
	if offset := smq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := smq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SubscriptionMatchGroupBy is the group-by builder for SubscriptionMatch entities.
type SubscriptionMatchGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (smgb *SubscriptionMatchGroupBy) Aggregate(fns ...AggregateFunc) *SubscriptionMatchGroupBy {
	smgb.fns = append(smgb.fns, fns...)
	return smgb
}

// Scan applies the group-by query and scans the result into the given value.
func (smgb *SubscriptionMatchGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := smgb.path(ctx)
	if err != nil {
		return err
	}
	smgb.sql = query
	return smgb.sqlScan(ctx, v)
}

func (smgb *SubscriptionMatchGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range smgb.fields {
		if !subscriptionmatch.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := smgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := smgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (smgb *SubscriptionMatchGroupBy) sqlQuery() *sql.Selector {
	selector := smgb.sql.Select()
	aggregation := make([]string, 0, len(smgb.fns))
	for _, fn := range smgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(smgb.fields)+len(smgb.fns))
		for _, f := range smgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(smgb.fields...)...)
}

// SubscriptionMatchSelect is the builder for selecting fields of SubscriptionMatch entities.
type SubscriptionMatchSelect struct {
	*SubscriptionMatchQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (sms *SubscriptionMatchSelect) Scan(ctx context.Context, v interface{}) error {
	if err := sms.prepareQuery(ctx); err != nil {
		return err
	}
	sms.sql = sms.SubscriptionMatchQuery.sqlQuery(ctx)
	return sms.sqlScan(ctx, v)
}

func (sms *SubscriptionMatchSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := sms.sql.Query()
	if err := sms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
